### PR TITLE
Export BoxesAndBubblesEngine

### PR DESCRIPTION
**Pull request by apatil**
This would help me optimize my air hockey game. :)

### CODE REVIEW

**Comment by jastice** [comment]
Hi!
How would it help? I'm reluctant to make the whole engine part of the public API, but maybe specific functions would be useful to expose?

**Comment by apatil** [comment]
I want to update the puck based on its collisions with the players' paddles and the walls of the rink, but don't need to update the paddles or the walls.

With `collideWith` and `update` exposed, I can compute the puck's collisions but skip computing collisions between the paddles and walls, as in https://github.com/apatil/elm-airhockey/blob/591f9608509947c9c508ae57fde35d06924165f1/airhockey.elm#L164.

[Edited, `collide` alone actually doesn't do the job.]

**Comment by jastice** [comment]
Hmm, I'll think about it :)
Meanwhile you can just copy the code you need, there won't be tons of changes in the near-term.

**Comment by apatil** [comment]
Hi @jastice, my two cents are that `collideWith` is low-level, but on the other hand consumers can probably count on its type signature remaining stable in future versions of your package. You're always going to have a reducer function in there, and its type is fairly constrained by the bodies types & the type of `collide`. 

Also, skipping collisions with objects of infinite mass is probably going to be a pretty common use case in any kind of game involving walls. On the other hand, even `collideWith` and `update` do some unnecessary computation in that case. Would you be interested in a new function or two that addresses that case more directly?

**Comment by jastice** [comment]
Hey, sorry for the long response time. I had lost my Macbook for a while ...

Regarding the structure, I'm a little unhappy with exporting things from 3 different modules, but I guess that's a bit of a limitation of Elm, lacking re-exporting. Anyway, B&B is not so popular that I can't afford some experimentation, so I'll just merge this :) Your suggestion sounds good too.

**Pull request merged**
